title: "Robotics Project"

url: "https://miltoti.github.io"
baseurl: "/106a_Website"

markdown: kramdown
kramdown:
  input: kramdown

description: "Project report scaffold for GitHub Pages"

exclude:
  - README.md
